apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-cost-optimizer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-cost-optimizer
rules:
# Pod and namespace access
- apiGroups: [""]
  resources: ["pods", "nodes", "namespaces", "services", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
# Deployment and workload access
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "patch"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
# Events access
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "get", "list", "watch"]
# ConfigMap and Secret access
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Storage access
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list"]
# Network policies
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-cost-optimizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-cost-optimizer
subjects:
- kind: ServiceAccount
  name: k8s-cost-optimizer
  namespace: kube-system 